---
abstract: 'A module that allows you to declare real exception classes in Perl'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exception-Class
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Exception-Class
  repository: git://git.urth.org/Exception-Class.git
version: 1.33
