---
name: Exception-Class
version: 1.21
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: A module that allows you to declare real exception classes in Perl
license: perl
requires:
  Class::Data::Inheritable: 0.02
  Devel::StackTrace: 1.1
  Scalar::Util: 0
  Test::More: 0.46
provides:
  Exception::Class:
    file: lib/Exception/Class.pm
    version: 1.21
  Exception::Class::Base:
    file: lib/Exception/Class.pm
    version: 1.21
generated_by: Module::Build version 0.2609
