#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Exception-Class
version:      1.13
version_from: Class.pm
installdirs:  site
requires:
    Test::More:                    0.46
    Devel::StackTrace:             1.03
    Class::Data::Inheritable:      0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_06
